openapi: "3.0.0"

info:
  title: API de App Roles
  version: "1.0.0"
  description: AppRole API

servers:
  - url: http://localhost:8080/app-admin/api

tags:
  - name: AppRole
    description: AppRole specific data.
paths:
  /appRoles:
    get:
      tags:
         - AppRole
      summary: Get All Actifs AppRoles
      operationId: getAllRoles
      parameters:
        - name: currentPage
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: sizePage
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
          '200':
            description: SUCCESS
            content:
              application/json:
                schema:
                  $ref: '../model/appRoles/AppRoleResultListDTO.yml'
          '404':
            description: NOT FOUND
          '400':
            description: BAD REQUEST
  /appRoles-reference:
           get:
              tags:
                  - AppRole
              summary: Retrieve an AppRole
              operationId: getAppRole
              parameters:
                  - name: idAppRole
                    in: path
                    required: true
                    schema:
                      type: integer
                      format: int64
              responses:
                  '200':
                    description: SUCCESS
                    content:
                      'application/json':
                       schema:
                          $ref: '../model/appRoles/AppRoleDTO.yml'
                  '404':
                    description: NOT FOUND
                  '400':
                    description: BAD REQUEST

