openapi: "3.0.0"

info:
  title: API de Produit
  version: "1.0"
  description: Produit API

servers:
  - url: http://localhost:8080/app-admin/api

tags:
  - name: Produit
    description: Produit specific data.
paths:
  /produits:
    get:
      tags:
        - Produit
      summary: Get All Actif Produit
      operationId: getAllProduits
      parameters:
        - name: currentPage
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: sizePage
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/produits/ProduitResultListDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST

  /produits-reference:
    get:
      tags:
        - Produit
      summary: Retrieve an Produit
      operationId: getProduit
      parameters:
        - name: idProduit
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/produits/ProduitDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST